baseURL: https://lyax.be
languageCode: nl-BE
title: Lyax
publishDir: docs
DefaultContentLanguage: nl
languages:
    nl:
        languageName: Nederlands
        params:
            description: Ik ben Kelly Alix
            tagline: Devilishly Good Support
            vat: BTW
            about: Over
    en:
        languageName: English
        params:
            description: I am Kelly Alix
            tagline: Devilishly Good Support
            vat: VAT
            about: About